# Main configuration file


# The ip-address for bind
# Posible values:
#   localhost, 127.0.0.1, 0.0.0.0
#   or the ip-address of any systtem ethernet interface
#
listen_address: 0.0.0.0

# The tcp-port for bind.
# Posible values:
#   80, 8080, 3000, or any from 1 - 65535
listen_port: 3000


# The workers number
# Use the same amount as you have CPUs
# correct values are:
# 1, 2, 3 ...
workers_amount: 2


# Waiting interval for worker to try get one more task
# The value in seconds
worker_loop_timeout: 1