# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82375887c941fd0a6aa46d2ba6a32a43257ebe47c7bfdc6be8016866dd35dc3769faf23839d91c29cb345bc7acd8557b098e06dc18a303f384cb1e57f8f6c81f

test:
  secret_key_base: d3cb4cd78f7c15d120cfa0aac254cb755b15db6e4928278e277a76bb990f814fe85339335419949e07ea733871a2f290762b26b83689f77d8d9733155dc8def0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
