source 'https://rubygems.org'
# Abbility to require (load ruby code) with whole folder
gem 'require_all'

# PostgreSQL driver
gem 'pg'

# rake task manager
gem 'rake'

# for STDOUT outpus colorization
gem 'colorize'

# for random data generation
gem 'forgery'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  # Call 'binding.pry' anywhere in the code to stop execution and get a debugger console
  gem 'pry-rails'
  gem 'pry-byebug'
end
