source 'https://rubygems.org'

gem 'logger'
gem 'require_all'

# TimeZone gem
gem 'tzinfo'
gem 'tzinfo-data'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
  gem 'pry-rails'
  gem 'pry-byebug'
end
